<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="assets/js/scripts.js"></script>
  <title>CRUD PHP</title>
</head>
<body>
  <header>
    <h1>CRUD PHP</h1>
  </header>
  <nav>
    <a href="/create">Create</a>
    <a href="/">Read</a>
  </nav>
  <main>
    <?= $content ?>
  </main>
  <footer>
    &copy; CRUD PHP
  </footer>
</body>
</html>
